/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author Javier
 */
public class AgendaRecepcionista extends javax.swing.JFrame {

    /**
     * Creates new form AgendaRecepcionista
     */
    public AgendaRecepcionista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnSalir = new javax.swing.JButton();
        LabelNombrePaciente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ComboDoctorACargo = new javax.swing.JComboBox<>();
        CampoBuscarPorNombre = new javax.swing.JTextField();
        BtnAgendarCita = new javax.swing.JButton();
        BtnReagendarCita = new javax.swing.JButton();
        BtnCancelarCita = new javax.swing.JButton();
        BtnConsultarInformacionCita = new javax.swing.JButton();
        BtnCerrarSesion = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        ComboEstadoCita = new javax.swing.JComboBox<>();
        BtnListaPacientes = new javax.swing.JToggleButton();
        BtnConsultarInfoPaciente = new javax.swing.JToggleButton();
        BtnRealizarCobro = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnSalir.setBackground(new java.awt.Color(255, 51, 0));
        BtnSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnSalir.setForeground(new java.awt.Color(255, 255, 255));
        BtnSalir.setText("Salir");
        BtnSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        LabelNombrePaciente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelNombrePaciente.setText("Nombre del paciente");

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Ricardo Javier Medina Caballero", "24/11/2024", "Querry Caver", "No completada"},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        ComboDoctorACargo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ComboDoctorACargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "doctor a cargo" }));
        ComboDoctorACargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboDoctorACargoActionPerformed(evt);
            }
        });

        CampoBuscarPorNombre.setBackground(new java.awt.Color(0, 102, 102));
        CampoBuscarPorNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CampoBuscarPorNombre.setForeground(new java.awt.Color(255, 255, 255));
        CampoBuscarPorNombre.setText("Buscar empleado por nombre");
        CampoBuscarPorNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BtnAgendarCita.setBackground(new java.awt.Color(0, 102, 102));
        BtnAgendarCita.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnAgendarCita.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgendarCita.setText("Agendar cita");
        BtnAgendarCita.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BtnReagendarCita.setBackground(new java.awt.Color(0, 102, 102));
        BtnReagendarCita.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnReagendarCita.setForeground(new java.awt.Color(255, 255, 255));
        BtnReagendarCita.setText("Reagendar cita");
        BtnReagendarCita.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BtnCancelarCita.setBackground(new java.awt.Color(0, 102, 102));
        BtnCancelarCita.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnCancelarCita.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelarCita.setText("Cancelar cita ");
        BtnCancelarCita.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnCancelarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarCitaActionPerformed(evt);
            }
        });

        BtnConsultarInformacionCita.setBackground(new java.awt.Color(0, 102, 102));
        BtnConsultarInformacionCita.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnConsultarInformacionCita.setForeground(new java.awt.Color(255, 255, 255));
        BtnConsultarInformacionCita.setText("Consultar informacion de la cita ");
        BtnConsultarInformacionCita.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BtnCerrarSesion.setBackground(new java.awt.Color(255, 153, 0));
        BtnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        BtnCerrarSesion.setText("Cerrar sesion");
        BtnCerrarSesion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarSesionActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fecha de la cita" }));

        ComboEstadoCita.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ComboEstadoCita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estado de la cita" }));

        BtnListaPacientes.setBackground(new java.awt.Color(0, 102, 102));
        BtnListaPacientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnListaPacientes.setForeground(new java.awt.Color(255, 255, 255));
        BtnListaPacientes.setText("Lista de pacientes ");
        BtnListaPacientes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BtnConsultarInfoPaciente.setBackground(new java.awt.Color(0, 102, 102));
        BtnConsultarInfoPaciente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnConsultarInfoPaciente.setForeground(new java.awt.Color(255, 255, 255));
        BtnConsultarInfoPaciente.setText("Consultar informacion de contacto");
        BtnConsultarInfoPaciente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BtnRealizarCobro.setBackground(new java.awt.Color(0, 102, 102));
        BtnRealizarCobro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnRealizarCobro.setForeground(new java.awt.Color(255, 255, 255));
        BtnRealizarCobro.setText("Realizar cobro");
        BtnRealizarCobro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(CampoBuscarPorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(BtnAgendarCita))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(LabelNombrePaciente)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnReagendarCita)
                                        .addGap(61, 61, 61)
                                        .addComponent(BtnCancelarCita)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(346, 346, 346)
                                        .addComponent(BtnCerrarSesion)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 34, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(BtnConsultarInformacionCita)
                                                .addGap(44, 44, 44)
                                                .addComponent(BtnListaPacientes))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ComboDoctorACargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(124, 124, 124)
                                                .addComponent(ComboEstadoCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(38, 38, 38))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnConsultarInfoPaciente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnRealizarCobro)))))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoBuscarPorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCerrarSesion)
                    .addComponent(BtnSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtnListaPacientes)
                        .addComponent(BtnConsultarInformacionCita))
                    .addComponent(BtnAgendarCita, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtnReagendarCita)
                        .addComponent(BtnCancelarCita)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ComboDoctorACargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ComboEstadoCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LabelNombrePaciente, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnConsultarInfoPaciente)
                    .addComponent(BtnRealizarCobro))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void ComboDoctorACargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboDoctorACargoActionPerformed
        ComboDoctorACargo.addItem("Doctor a cargo");
    }//GEN-LAST:event_ComboDoctorACargoActionPerformed

    private void BtnCancelarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCancelarCitaActionPerformed

    private void BtnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendaRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendaRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendaRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendaRecepcionista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgendarCita;
    private javax.swing.JButton BtnCancelarCita;
    private javax.swing.JButton BtnCerrarSesion;
    private javax.swing.JToggleButton BtnConsultarInfoPaciente;
    private javax.swing.JButton BtnConsultarInformacionCita;
    private javax.swing.JToggleButton BtnListaPacientes;
    private javax.swing.JButton BtnReagendarCita;
    private javax.swing.JToggleButton BtnRealizarCobro;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JTextField CampoBuscarPorNombre;
    private javax.swing.JComboBox<String> ComboDoctorACargo;
    private javax.swing.JComboBox<String> ComboEstadoCita;
    private javax.swing.JLabel LabelNombrePaciente;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
