/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author Javier
 */
public class ModificarInformacionEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form ModificarInformacionEmpleado
     */
    public ModificarInformacionEmpleado() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelNombres = new javax.swing.JLabel();
        CampoNombres = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        LabelApellidos = new javax.swing.JLabel();
        CampoApellidos = new javax.swing.JTextField();
        CampoFechaIngreso = new javax.swing.JTextField();
        CampoNombreUsuario = new javax.swing.JTextField();
        CampoContraseña = new javax.swing.JTextField();
        CampoCorreo = new javax.swing.JTextField();
        CampoNumeroTelefonico = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        LabelFechaIngreso = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        LabelNombreUsuario = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        LabelContraseña = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        LabelCorreoElectronico = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        LabelNumeroTelefonico = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        LabelTipoEmpleado = new javax.swing.JLabel();
        CampoTipoEmpleado = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        BtnCancelar = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelNombres.setBackground(new java.awt.Color(102, 102, 102));
        LabelNombres.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelNombres.setForeground(new java.awt.Color(255, 255, 255));
        LabelNombres.setText("Nombres ");
        getContentPane().add(LabelNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        CampoNombres.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CampoNombres.setForeground(new java.awt.Color(153, 153, 153));
        CampoNombres.setText("Ricardo Javier ");
        getContentPane().add(CampoNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        LabelApellidos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelApellidos.setForeground(new java.awt.Color(255, 255, 255));
        LabelApellidos.setText("Apellidos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelApellidos)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelApellidos)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 110, 40));

        CampoApellidos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CampoApellidos.setForeground(new java.awt.Color(153, 153, 153));
        CampoApellidos.setText("Medina Caballero");
        getContentPane().add(CampoApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        CampoFechaIngreso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CampoFechaIngreso.setForeground(new java.awt.Color(153, 153, 153));
        CampoFechaIngreso.setText("DD/MM/AAAA");
        getContentPane().add(CampoFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        CampoNombreUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CampoNombreUsuario.setForeground(new java.awt.Color(153, 153, 153));
        CampoNombreUsuario.setText("JAVIERMC3333333333");
        getContentPane().add(CampoNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

        CampoContraseña.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CampoContraseña.setForeground(new java.awt.Color(153, 153, 153));
        CampoContraseña.setText("AAAAAAAAAAAA");
        getContentPane().add(CampoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, -1, -1));

        CampoCorreo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CampoCorreo.setForeground(new java.awt.Color(153, 153, 153));
        CampoCorreo.setText("correo@hotmail.com");
        getContentPane().add(CampoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, -1, -1));

        CampoNumeroTelefonico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CampoNumeroTelefonico.setForeground(new java.awt.Color(153, 153, 153));
        CampoNumeroTelefonico.setText("9999999999");
        getContentPane().add(CampoNumeroTelefonico, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        LabelFechaIngreso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelFechaIngreso.setForeground(new java.awt.Color(255, 255, 255));
        LabelFechaIngreso.setText("Fecha de ingreso");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelFechaIngreso)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelFechaIngreso)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 160, 40));

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        LabelNombreUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        LabelNombreUsuario.setText("Nombre de usuario");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelNombreUsuario)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelNombreUsuario)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 180, 40));

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));

        LabelContraseña.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelContraseña.setForeground(new java.awt.Color(255, 255, 255));
        LabelContraseña.setText("Contraseña");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelContraseña)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(LabelContraseña)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 110, 30));

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));

        LabelCorreoElectronico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelCorreoElectronico.setForeground(new java.awt.Color(255, 255, 255));
        LabelCorreoElectronico.setText("Correo electronico");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(LabelCorreoElectronico)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelCorreoElectronico)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 170, 40));

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));

        LabelNumeroTelefonico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelNumeroTelefonico.setForeground(new java.awt.Color(255, 255, 255));
        LabelNumeroTelefonico.setText("Número de telefono");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelNumeroTelefonico)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelNumeroTelefonico)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 190, 40));

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));

        LabelTipoEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelTipoEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        LabelTipoEmpleado.setText("Tipo de empleado");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTipoEmpleado)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(LabelTipoEmpleado)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 180, 30));

        CampoTipoEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CampoTipoEmpleado.setForeground(new java.awt.Color(153, 153, 153));
        CampoTipoEmpleado.setText("Administrador");
        getContentPane().add(CampoTipoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, -1, -1));

        jPanel10.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 50));

        BtnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(0, 51, 255));
        BtnCancelar.setText("Cancelar");
        BtnCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 520, -1, -1));

        jPanel11.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Detalles del empleado");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 290, 50));

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        jButton1.setBackground(new java.awt.Color(255, 102, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Guardar cambios");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(553, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(157, 157, 157))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 296, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 860, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarInformacionEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarInformacionEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarInformacionEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarInformacionEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarInformacionEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JTextField CampoApellidos;
    private javax.swing.JTextField CampoContraseña;
    private javax.swing.JTextField CampoCorreo;
    private javax.swing.JTextField CampoFechaIngreso;
    private javax.swing.JTextField CampoNombreUsuario;
    private javax.swing.JTextField CampoNombres;
    private javax.swing.JTextField CampoNumeroTelefonico;
    private javax.swing.JTextField CampoTipoEmpleado;
    private javax.swing.JLabel LabelApellidos;
    private javax.swing.JLabel LabelContraseña;
    private javax.swing.JLabel LabelCorreoElectronico;
    private javax.swing.JLabel LabelFechaIngreso;
    private javax.swing.JLabel LabelNombreUsuario;
    private javax.swing.JLabel LabelNombres;
    private javax.swing.JLabel LabelNumeroTelefonico;
    private javax.swing.JLabel LabelTipoEmpleado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
