/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author Javier
 */
public class RecetaMedica extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaMedica
     */
    public RecetaMedica() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelRecetaMedica = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        LabelEmitidaPor = new javax.swing.JLabel();
        CampoNombreDoctor = new javax.swing.JTextField();
        LabelFirmaDoctor = new javax.swing.JLabel();
        LabelCedula = new javax.swing.JLabel();
        CampoCedulaDoctor = new javax.swing.JTextField();
        BtnGuardarReceta = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelRecetaMedica.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        LabelRecetaMedica.setText("RECETA MEDICA ");
        jPanel1.add(LabelRecetaMedica, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Fecha ", "12/11/2024"}
            },
            new String [] {
                "Información del paciente", ""
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 175, 312, 67));

        jTable2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"KETOROLACO 200 mg", "1 cada 8 horas ", "1 semana "},
                {"Troferit flow 3 mg/ml", "1 cucharada cada 6 horas", "2 semanas"}
            },
            new String [] {
                "Nombre del medicamento", "Dosis", "Duración"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 276, 571, 100));

        LabelEmitidaPor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelEmitidaPor.setText("Emitida por: ");
        jPanel1.add(LabelEmitidaPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 449, -1, -1));

        CampoNombreDoctor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CampoNombreDoctor.setText("Juan Garcia ");
        jPanel1.add(CampoNombreDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 446, -1, -1));

        LabelFirmaDoctor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelFirmaDoctor.setText("Firma del doctor");
        jPanel1.add(LabelFirmaDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 658, -1, -1));

        LabelCedula.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelCedula.setText("Con cédula: ");
        jPanel1.add(LabelCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 658, -1, -1));

        CampoCedulaDoctor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CampoCedulaDoctor.setText("12345");
        jPanel1.add(CampoCedulaDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 655, -1, -1));

        BtnGuardarReceta.setBackground(new java.awt.Color(0, 102, 102));
        BtnGuardarReceta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnGuardarReceta.setForeground(new java.awt.Color(255, 255, 255));
        BtnGuardarReceta.setText("Guardar receta ");
        BtnGuardarReceta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(BtnGuardarReceta, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 580, 163, -1));

        BtnCancelar.setBackground(new java.awt.Color(255, 51, 51));
        BtnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelar.setText("Cancelar");
        BtnCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 630, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_for_a_pharmaceutical_company__1_-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 450, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/logo_for_a_pharmaceutical_company__1_-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecetaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecetaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecetaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecetaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecetaMedica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnGuardarReceta;
    private javax.swing.JTextField CampoCedulaDoctor;
    private javax.swing.JTextField CampoNombreDoctor;
    private javax.swing.JLabel LabelCedula;
    private javax.swing.JLabel LabelEmitidaPor;
    private javax.swing.JLabel LabelFirmaDoctor;
    private javax.swing.JLabel LabelRecetaMedica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
