/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author Javier
 */
public class ReciboPagoVenta extends javax.swing.JFrame {

    /**
     * Creates new form ReciboPagoVenta
     */
    public ReciboPagoVenta() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LabelReciboPagoVenta = new javax.swing.JLabel();
        LabelFechaCompra = new javax.swing.JLabel();
        CampoFechaCompra = new javax.swing.JTextField();
        LabelHoraCompra = new javax.swing.JLabel();
        CampoHoraDeCompra = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        LabelTotalVenta = new javax.swing.JLabel();
        CampoTotalVenta = new javax.swing.JTextField();
        LabelMontoEntregadoVenta = new javax.swing.JLabel();
        CampoMontoEntregadoVenta = new javax.swing.JTextField();
        LabelCambioVenta = new javax.swing.JLabel();
        CampoCambioVenta = new javax.swing.JTextField();
        BtnGenerarReciboVenta = new javax.swing.JButton();
        BtnCancelarVenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        LabelReciboPagoVenta.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        LabelReciboPagoVenta.setText("RECIBO DE PAGO DE VENTA");

        LabelFechaCompra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelFechaCompra.setText("Fecha de la compra: ");

        LabelHoraCompra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelHoraCompra.setText("Hora de la compra:");

        CampoHoraDeCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoHoraDeCompraActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Paracetamol  500mg ", "3", "$130.00"},
                {"KETOROLACO 200 mg", "2", "$232.00"},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Precio unitario"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        LabelTotalVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelTotalVenta.setText("Total:");

        CampoTotalVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CampoTotalVenta.setText("$800.00");

        LabelMontoEntregadoVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelMontoEntregadoVenta.setText("Monto entregado: ");

        CampoMontoEntregadoVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CampoMontoEntregadoVenta.setText("$1000.00");

        LabelCambioVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelCambioVenta.setText("Cambio:");

        CampoCambioVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CampoCambioVenta.setText("$200.00");
        CampoCambioVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCambioVentaActionPerformed(evt);
            }
        });

        BtnGenerarReciboVenta.setBackground(new java.awt.Color(0, 102, 102));
        BtnGenerarReciboVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnGenerarReciboVenta.setForeground(new java.awt.Color(255, 255, 255));
        BtnGenerarReciboVenta.setText("Generar e imprimir recibo");
        BtnGenerarReciboVenta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BtnCancelarVenta.setBackground(new java.awt.Color(255, 51, 51));
        BtnCancelarVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnCancelarVenta.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelarVenta.setText("Cancelar");
        BtnCancelarVenta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnCancelarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarVentaActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/logo_for_a_pharmaceutical_company__1_-removebg-preview.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(LabelTotalVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoTotalVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelMontoEntregadoVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoMontoEntregadoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(LabelCambioVenta)
                .addGap(18, 18, 18)
                .addComponent(CampoCambioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnCancelarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelFechaCompra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoFechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(LabelHoraCompra)
                        .addGap(18, 18, 18)
                        .addComponent(CampoHoraDeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelReciboPagoVenta)
                        .addGap(179, 179, 179))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnGenerarReciboVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelReciboPagoVenta)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelFechaCompra)
                            .addComponent(CampoFechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelHoraCompra)
                            .addComponent(CampoHoraDeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(BtnGenerarReciboVenta)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTotalVenta)
                    .addComponent(CampoTotalVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelMontoEntregadoVenta)
                    .addComponent(CampoMontoEntregadoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCambioVenta)
                    .addComponent(CampoCambioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCancelarVenta))
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 997, 647));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoHoraDeCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoHoraDeCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoHoraDeCompraActionPerformed

    private void BtnCancelarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCancelarVentaActionPerformed

    private void CampoCambioVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCambioVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCambioVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReciboPagoVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReciboPagoVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReciboPagoVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReciboPagoVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReciboPagoVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelarVenta;
    private javax.swing.JButton BtnGenerarReciboVenta;
    private javax.swing.JTextField CampoCambioVenta;
    private javax.swing.JTextField CampoFechaCompra;
    private javax.swing.JTextField CampoHoraDeCompra;
    private javax.swing.JTextField CampoMontoEntregadoVenta;
    private javax.swing.JTextField CampoTotalVenta;
    private javax.swing.JLabel LabelCambioVenta;
    private javax.swing.JLabel LabelFechaCompra;
    private javax.swing.JLabel LabelHoraCompra;
    private javax.swing.JLabel LabelMontoEntregadoVenta;
    private javax.swing.JLabel LabelReciboPagoVenta;
    private javax.swing.JLabel LabelTotalVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
