/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author Javier
 */
public class ReciboPagoConsulta extends javax.swing.JFrame {

    /**
     * Creates new form ReciboPagoConsulta
     */
    public ReciboPagoConsulta() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelReciboConsulta = new javax.swing.JLabel();
        LabelCantidad = new javax.swing.JLabel();
        CampoCantidad = new javax.swing.JTextField();
        LabelNombreDoctor = new javax.swing.JLabel();
        CampoNombreDoctor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaFechaDeConsulta = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaFechaDePago = new javax.swing.JTable();
        LabelTotal = new javax.swing.JLabel();
        CampoTotal = new javax.swing.JTextField();
        LabelMontoEntregado = new javax.swing.JLabel();
        CampoMontoEntregado = new javax.swing.JTextField();
        LabelCambio = new javax.swing.JLabel();
        CampoCambio = new javax.swing.JTextField();
        BtnGenerarRecibo = new javax.swing.JToggleButton();
        BtnCancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, -1));

        LabelReciboConsulta.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        LabelReciboConsulta.setText("RECIBO DE PAGO DE CONSULTA");
        getContentPane().add(LabelReciboConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 85, -1, -1));

        LabelCantidad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelCantidad.setText("Cantidad:");
        getContentPane().add(LabelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 225, -1, -1));

        CampoCantidad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CampoCantidad.setText("$250.00");
        CampoCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCantidadActionPerformed(evt);
            }
        });
        getContentPane().add(CampoCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 222, -1, -1));

        LabelNombreDoctor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelNombreDoctor.setText("Nombre del doctor: ");
        getContentPane().add(LabelNombreDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 283, -1, -1));

        CampoNombreDoctor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CampoNombreDoctor.setText("Querry CAver");
        CampoNombreDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNombreDoctorActionPerformed(evt);
            }
        });
        getContentPane().add(CampoNombreDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 283, -1, -1));

        TablaFechaDeConsulta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TablaFechaDeConsulta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TablaFechaDeConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"11/11/2024", "10:30 am"}
            },
            new String [] {
                "Fecha de consulta", "Hora de consulta"
            }
        ));
        jScrollPane1.setViewportView(TablaFechaDeConsulta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 344, 249, 66));

        TablaFechaDePago.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TablaFechaDePago.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TablaFechaDePago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"12/11/2024", "11:30 am"}
            },
            new String [] {
                "Fecha ", "Hora "
            }
        ));
        jScrollPane2.setViewportView(TablaFechaDePago);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 443, 249, 64));

        LabelTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelTotal.setText("Total:");
        getContentPane().add(LabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 617, -1, -1));

        CampoTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CampoTotal.setText("$250.00");
        getContentPane().add(CampoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 614, -1, -1));

        LabelMontoEntregado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelMontoEntregado.setText("Monto entregado:");
        getContentPane().add(LabelMontoEntregado, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 617, -1, -1));

        CampoMontoEntregado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CampoMontoEntregado.setText("$300");
        CampoMontoEntregado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoMontoEntregadoActionPerformed(evt);
            }
        });
        getContentPane().add(CampoMontoEntregado, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 614, -1, -1));

        LabelCambio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelCambio.setText("Cambio:");
        getContentPane().add(LabelCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 617, -1, -1));

        CampoCambio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CampoCambio.setText("$50");
        getContentPane().add(CampoCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 614, -1, -1));

        BtnGenerarRecibo.setBackground(new java.awt.Color(0, 102, 102));
        BtnGenerarRecibo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnGenerarRecibo.setForeground(new java.awt.Color(255, 255, 255));
        BtnGenerarRecibo.setText("Generar e imprimir recibo");
        BtnGenerarRecibo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(BtnGenerarRecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 543, -1, -1));

        BtnCancelar.setBackground(new java.awt.Color(255, 51, 51));
        BtnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelar.setText("Cancelar");
        BtnCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(859, 605, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/logo_for_a_pharmaceutical_company__1_-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(540, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCantidadActionPerformed

    private void CampoNombreDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNombreDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNombreDoctorActionPerformed

    private void CampoMontoEntregadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoMontoEntregadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoMontoEntregadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReciboPagoConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReciboPagoConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReciboPagoConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReciboPagoConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReciboPagoConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JToggleButton BtnGenerarRecibo;
    private javax.swing.JTextField CampoCambio;
    private javax.swing.JTextField CampoCantidad;
    private javax.swing.JTextField CampoMontoEntregado;
    private javax.swing.JTextField CampoNombreDoctor;
    private javax.swing.JTextField CampoTotal;
    private javax.swing.JLabel LabelCambio;
    private javax.swing.JLabel LabelCantidad;
    private javax.swing.JLabel LabelMontoEntregado;
    private javax.swing.JLabel LabelNombreDoctor;
    private javax.swing.JLabel LabelReciboConsulta;
    private javax.swing.JLabel LabelTotal;
    private javax.swing.JTable TablaFechaDeConsulta;
    private javax.swing.JTable TablaFechaDePago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
